server:
  port: 8085
spring:
  application:
    name: trade-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${hm.db.host}:${hm.db.port}/hm-trade?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw}
  cloud:
    consul:
      host: ${hm.consul.host}
      port: ${hm.consul.port}
      discovery:
        hostname: ${spring.cloud.client.ip-address}
        instance-id: ${spring.application.name}:${spring.cloud.consul.discovery.hostname}:${server.port}
        register: true
        register-health-check: true
#        health-check-path: ${server.servlet.context-path}/actuator/health
        healthCheckInterval: 15s
        service-name: ${spring.application.name} #指定注册的服务名称 默认就是应用名
# actuator放开端口
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: 黑马商城交易管理接口文档
    description: "黑马商城交易管理接口文档"
    email: zhanghuyi@itcast.cn
    concat: 虎哥
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hmall.trade.controller # Swagger扫描到Controller,会把Controller接口信息作为接口文档信息