server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**,/search/**
#          filters:
#            - AddRequestHeader=headerName, headerValue
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/addresses/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
        - id: trade-service
          uri: lb://trade-service
          predicates:
            - Path=/orders/**
#      default-filters:
#        - AddRequestHeader=headerName, headerValue
    consul:
      host: ${hm.consul.host}
      port: ${hm.consul.port}
      discovery:
        hostname: ${spring.cloud.client.ip-address}
        instance-id: ${spring.application.name}:${spring.cloud.consul.discovery.hostname}:${server.port}
        register: true
        register-health-check: true
        #        health-check-path: ${server.servlet.context-path}/actuator/health
        healthCheckInterval: 15s
        service-name: ${spring.application.name} #指定注册的服务名称 默认就是应用名